name: Deploy Docker app to AWS Elastic Beanstalk

# Trigger workflow on push to main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo code
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Install Elastic Beanstalk CLI
        run: pip install awsebcli

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Initialize Elastic Beanstalk app
        run: eb init pantheonplus-regression --platform docker --region ap-south-1

      - name: Select environment
        run: eb use Pantheonplus-regression-env

      - name: Deploy to Elastic Beanstalk
        run: eb deploy
